// Auto-generated by tracker.py — do not edit
var LTC_DATA = {
  "transactions": [
    {
      "txid": "ce83ed0020245c85a8128c06cd265ad10311e2eb42b0a89245ac2b87f658808f",
      "date": "2025-02-21",
      "timestamp": "2025-02-21T13:25:29+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.76860722,
      "net_ltc": 1.76860722,
      "price_usd": 128.09
    },
    {
      "txid": "d1454e7413e23d8752e2a66f65a6eb500764e6b401da2926c7013982ba948bc8",
      "date": "2025-02-24",
      "timestamp": "2025-02-24T13:14:33+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 2.10713996,
      "net_ltc": 2.10713996,
      "price_usd": 114.78
    },
    {
      "txid": "5942aeb2fae01f675e2a63500e61cc261b0058a48755bf54464c9f1d05abf64b",
      "date": "2025-02-24",
      "timestamp": "2025-02-24T13:26:25+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 2.10713996,
      "net_ltc": -2.10713996,
      "price_usd": 114.78
    },
    {
      "txid": "61d158cd0347ab633a33d728648c1bc9b551d8eb05902093ec8930f5daee04c9",
      "date": "2025-02-24",
      "timestamp": "2025-02-24T13:56:28+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.59171045,
      "net_ltc": 0.59171045,
      "price_usd": 114.78
    },
    {
      "txid": "a23a6e9e6e9b3748d5805b571c0991350e417ae02fed2a84374dca78442fc9b8",
      "date": "2025-02-24",
      "timestamp": "2025-02-24T14:07:00+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.59171045,
      "net_ltc": -0.59171045,
      "price_usd": 114.78
    },
    {
      "txid": "54caa65a5209efadaa4eea547ccb4aa90e47a91b95e57395c479d78320a2c4c5",
      "date": "2025-03-01",
      "timestamp": "2025-03-01T13:16:23+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.14364044,
      "net_ltc": 0.14364044,
      "price_usd": 124.28
    },
    {
      "txid": "6af1b726cefc3ebe59471389c167913f086c3d98fe0edf3d0295577c12c7bf25",
      "date": "2025-03-01",
      "timestamp": "2025-03-01T13:34:04+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.14364044,
      "net_ltc": -0.14364044,
      "price_usd": 124.28
    },
    {
      "txid": "fdf5bbf672936e1127c14c12fce078b3b91bebaf6f52c3a70a141412f54153ec",
      "date": "2025-04-15",
      "timestamp": "2025-04-15T16:52:58+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.08841087,
      "net_ltc": 1.08841087,
      "price_usd": 75.27
    },
    {
      "txid": "3f5ba0d3d73a8bd01c39a0feacab6bfe2e39fa836208e16944757909431db725",
      "date": "2025-04-21",
      "timestamp": "2025-04-21T03:11:36+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.08841087,
      "net_ltc": -1.08841087,
      "price_usd": 78.12
    },
    {
      "txid": "92098b82c2f11d97d473184f94e1868a037e4eea090b374164dc2f5e74c79d71",
      "date": "2025-04-22",
      "timestamp": "2025-04-22T07:31:12+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 8.77242266,
      "net_ltc": 8.77242266,
      "price_usd": 83.52
    },
    {
      "txid": "f6d305a83127025714d4582c0469c567add0695bda7d0acd7bc897fe80f57d3b",
      "date": "2025-04-26",
      "timestamp": "2025-04-26T23:14:06+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 8.77242266,
      "net_ltc": -8.77242266,
      "price_usd": 87.11
    },
    {
      "txid": "596c4fbcdcc55e2f60422861c0b45c50fb391f204c7e34adf3bbbf0c13b74f5a",
      "date": "2025-05-15",
      "timestamp": "2025-05-15T09:11:25+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.76491277,
      "net_ltc": 0.76491277,
      "price_usd": 99.28
    },
    {
      "txid": "1fbcabdba5003cbb3a7f4d94c89c21508a7b361b9bce9b157de080d40591a741",
      "date": "2025-05-22",
      "timestamp": "2025-05-22T00:15:26+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.76491277,
      "net_ltc": -0.76491277,
      "price_usd": 100.28
    },
    {
      "txid": "e4315d319a088a4d19e5cd2fc01f9e27f0ee95833b1fc65e29a5b04c2c4f321f",
      "date": "2025-05-22",
      "timestamp": "2025-05-22T07:29:40+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 3.86588426,
      "net_ltc": 3.86588426,
      "price_usd": 100.28
    },
    {
      "txid": "b51f179c57f12d573f156994950a8a4f3edca92a04bcbb22ca9e2f39fd318e31",
      "date": "2025-05-27",
      "timestamp": "2025-05-27T12:21:24+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 3.86588426,
      "net_ltc": -3.86588426,
      "price_usd": 95.95
    },
    {
      "txid": "250effdc9ee3f006f658e5f843c6581251d61619d5a50e04678146ae5e2d36a8",
      "date": "2025-06-26",
      "timestamp": "2025-06-26T15:28:59+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 2.96637252,
      "net_ltc": 2.96637252,
      "price_usd": 84.33
    },
    {
      "txid": "646febd90e3d1ba0f95481f2064a43a95b9f3c9b24a277753afde3b135a65447",
      "date": "2025-07-05",
      "timestamp": "2025-07-05T21:00:21+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 29.0,
      "net_ltc": 29.0,
      "price_usd": 87.6
    },
    {
      "txid": "a78966a935d76ad9ced71af2c570c54f393c492fd52ebfabf9769ddbb4e9ec5e",
      "date": "2025-07-18",
      "timestamp": "2025-07-18T19:25:55+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 2.96637252,
      "net_ltc": -2.96637252,
      "price_usd": 101.77
    },
    {
      "txid": "ecf038bd7a3381213d258580165e08e91a624c55aeb335bba689f0fdeaa68e13",
      "date": "2025-07-21",
      "timestamp": "2025-07-21T11:31:17+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.96929617,
      "net_ltc": 1.96929617,
      "price_usd": 115.52
    },
    {
      "txid": "536a90bc1671374f0cd88b75f8f9bd55480fe05003b6cf1e650fa7d575ad0f81",
      "date": "2025-07-24",
      "timestamp": "2025-07-24T20:09:35+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.96929617,
      "net_ltc": -1.96929617,
      "price_usd": 112.29
    },
    {
      "txid": "dc152bbff35cee425ed8d02a3dc36f9cbfd7f5485edbe548c17be26bb42d1f38",
      "date": "2025-08-13",
      "timestamp": "2025-08-13T12:11:54+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.89724995,
      "net_ltc": 1.89724995,
      "price_usd": 130.93
    },
    {
      "txid": "fd3425b4b9458b0f308e0786b5f2e07a339e05d7d307d9572cc220434f2309a8",
      "date": "2025-08-13",
      "timestamp": "2025-08-13T12:44:08+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.89724995,
      "net_ltc": -1.89724995,
      "price_usd": 130.93
    },
    {
      "txid": "9501cc619ef7d4080576da0d2cc737366885d32a9dda1b7178ce7e571265d535",
      "date": "2025-08-14",
      "timestamp": "2025-08-14T13:54:58+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.62399999,
      "net_ltc": 1.62399999,
      "price_usd": 121.37
    },
    {
      "txid": "0898b1625755041d823272b4a1fb3c5ca2d07a2d1cb8658b59b672da957ca402",
      "date": "2025-08-14",
      "timestamp": "2025-08-14T14:58:41+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.62399999,
      "net_ltc": -1.62399999,
      "price_usd": 121.37
    },
    {
      "txid": "08d672ddb56ed1db5a7cb0fb4b5c51dbb4a8ae4732c4d8d911a344f16617d755",
      "date": "2025-08-16",
      "timestamp": "2025-08-16T12:34:44+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 5.81992074,
      "net_ltc": 5.81992074,
      "price_usd": 121.11
    },
    {
      "txid": "893f6e46eccfb974a199f83bab93e83093e4578ed65d33d897e5c9bac786e898",
      "date": "2025-08-19",
      "timestamp": "2025-08-19T15:51:52+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.87505205,
      "net_ltc": 0.87505205,
      "price_usd": 112.65
    },
    {
      "txid": "fb7f1f2db1aee55209c4b27adffb4ea564f8c0968423c44254f849ca6fab03a8",
      "date": "2025-08-19",
      "timestamp": "2025-08-19T16:52:39+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.87505205,
      "net_ltc": -0.87505205,
      "price_usd": 112.65
    },
    {
      "txid": "4714a88899fc08bec498cca66f647a7eb28275718b89889476ab1ac9b2a58de3",
      "date": "2025-08-28",
      "timestamp": "2025-08-28T16:43:05+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.5199,
      "net_ltc": -0.5199,
      "price_usd": 113.69
    },
    {
      "txid": "88b5c95e9fa1492ad7fc741e5566223113ffa2bd84970bdabd40b10d9b91b495",
      "date": "2025-08-29",
      "timestamp": "2025-08-29T11:16:51+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.10891363,
      "net_ltc": 0.10891363,
      "price_usd": 109.93
    },
    {
      "txid": "eeae7afc85a5f27e11291d9bc0383c4417c3a4e8ceeebe738e2660ae65daf103",
      "date": "2025-08-29",
      "timestamp": "2025-08-29T11:38:16+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.90917344,
      "net_ltc": 0.90917344,
      "price_usd": 109.93
    },
    {
      "txid": "dbdf2ab8e1bf55eb11b8bd00efb8f538d8dc8e62d7ed188911345c6173c959c3",
      "date": "2025-08-29",
      "timestamp": "2025-08-29T11:53:25+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.36444777,
      "net_ltc": 1.36444777,
      "price_usd": 109.93
    },
    {
      "txid": "f9dedd31f57655bff2d58560dca8fdc3e18295eb4453c35f40b0f8af004cf84e",
      "date": "2025-08-29",
      "timestamp": "2025-08-29T11:53:25+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.90917344,
      "net_ltc": -0.90917344,
      "price_usd": 109.93
    },
    {
      "txid": "8c6259bf579f4f3030487e9957d2e16056c2bd98ddc95155fb4290b062d88e40",
      "date": "2025-08-29",
      "timestamp": "2025-08-29T12:33:28+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.36444777,
      "net_ltc": -1.36444777,
      "price_usd": 109.93
    },
    {
      "txid": "fddf5a129a1939c68ad99359dbfc017f2fb3f6fad052db12f640d0bf880029d2",
      "date": "2025-09-13",
      "timestamp": "2025-09-13T13:59:36+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.34022944,
      "net_ltc": 0.34022944,
      "price_usd": 119.3
    },
    {
      "txid": "ee2c4085aeebd01b64fd7a83cf031f687284663117d00e33d93d84e7a1c5d3f0",
      "date": "2025-09-13",
      "timestamp": "2025-09-13T19:25:28+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.34022944,
      "net_ltc": -0.34022944,
      "price_usd": 119.3
    },
    {
      "txid": "b92ddd54815e60b2d0c028477a1a03263e7ccdb2f749ef07be80588262dbeb6a",
      "date": "2025-09-18",
      "timestamp": "2025-09-18T13:17:32+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 2.55219527,
      "net_ltc": 2.55219527,
      "price_usd": 118.27
    },
    {
      "txid": "84b1951cb4b9112c38bd4cc9427fbfb031cd61c2923dfb0fb703cd02e16d3b5e",
      "date": "2025-09-18",
      "timestamp": "2025-09-18T13:37:10+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 2.55219527,
      "net_ltc": -2.55219527,
      "price_usd": 118.27
    },
    {
      "txid": "5123db3ba3c30e73bdf8b3dee0c6ba2c5442974dfe1d9cb1b41b55c9fe1167a8",
      "date": "2025-09-22",
      "timestamp": "2025-09-22T19:42:51+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.95229996,
      "net_ltc": 0.95229996,
      "price_usd": 105.78
    },
    {
      "txid": "a590ad2b25419fa06ccbc813ab7245eda9a11387427434b196b9234ee6a56b69",
      "date": "2025-09-22",
      "timestamp": "2025-09-22T19:58:09+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.95229996,
      "net_ltc": -0.95229996,
      "price_usd": 105.78
    },
    {
      "txid": "d14ae91c6d73352e58c5928252210c289ada2f06e82801f503bbd5a7c1fc0b20",
      "date": "2025-09-23",
      "timestamp": "2025-09-23T11:46:41+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.12680655,
      "net_ltc": 1.12680655,
      "price_usd": 106.12
    },
    {
      "txid": "3bc38145363abeb36ebcf17b7457800fdf0186aff8f7f39f51a04192af0b5f28",
      "date": "2025-09-23",
      "timestamp": "2025-09-23T11:58:57+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.12680655,
      "net_ltc": -1.12680655,
      "price_usd": 106.12
    },
    {
      "txid": "bf6bc5ed8208df05aacb34bcae0be7fbefb059ce847495eac2eaef7b88ddf965",
      "date": "2025-10-10",
      "timestamp": "2025-10-10T15:01:20+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.37740423,
      "net_ltc": 1.37740423,
      "price_usd": 98.92
    },
    {
      "txid": "cebb955fce3bfed68046e6fe100a25f1f9d67dc392f3afb291c533ff22e58c53",
      "date": "2025-10-10",
      "timestamp": "2025-10-10T15:10:28+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.37740423,
      "net_ltc": -1.37740423,
      "price_usd": 98.92
    },
    {
      "txid": "dfe058b3a74dab8cc754b01f8940009f38b941d622e2e73d4a481cd4fdd2988f",
      "date": "2025-10-15",
      "timestamp": "2025-10-15T10:53:20+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.45830416,
      "net_ltc": 1.45830416,
      "price_usd": 95.57
    },
    {
      "txid": "0fc3e3e73eaa984840bf8696b533d56a3a2aeb77bc05e649080f315a4c2e4442",
      "date": "2025-10-15",
      "timestamp": "2025-10-15T11:24:31+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.45830416,
      "net_ltc": -1.45830416,
      "price_usd": 95.57
    },
    {
      "txid": "302180c3efa01fd5ad9f00394cecc33b696bde807da395d657aed39a200ee605",
      "date": "2025-10-17",
      "timestamp": "2025-10-17T13:57:16+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 5.81992074,
      "net_ltc": -5.81992074,
      "price_usd": 90.15
    },
    {
      "txid": "df2beea6e818fb8925060eaca8cb7c27bc98202d714745841444113ec73330c9",
      "date": "2025-10-20",
      "timestamp": "2025-10-20T10:10:56+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.73982259,
      "net_ltc": 0.73982259,
      "price_usd": 94.03
    },
    {
      "txid": "4b35a8eed9c498177ec9619fd6fb4d826215316f5ed06ed43626b8ff92e0d68f",
      "date": "2025-10-20",
      "timestamp": "2025-10-20T14:27:17+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.73982259,
      "net_ltc": -0.73982259,
      "price_usd": 94.03
    },
    {
      "txid": "b8dc2ef75adb56d6dca9687792b586c25375e3cd19bd39df73b5ee52c6917fb7",
      "date": "2025-10-29",
      "timestamp": "2025-10-29T12:04:50+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.82771157,
      "net_ltc": 1.82771157,
      "price_usd": 98.51
    },
    {
      "txid": "a653a6eb0c2720ddad5dc16dccfc22b75a8325a362069f44bbcba35952c2d9c0",
      "date": "2025-10-29",
      "timestamp": "2025-10-29T12:41:34+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.82771157,
      "net_ltc": -1.82771157,
      "price_usd": 98.51
    },
    {
      "txid": "551024e4693f7bdeb02f199f5fa3dac338851232eaa9d3317bdcc888c2552b90",
      "date": "2025-10-30",
      "timestamp": "2025-10-30T12:35:42+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 7.01760035,
      "net_ltc": 7.01760035,
      "price_usd": 93.4
    },
    {
      "txid": "77d7eed5896906806e48c2bcc6d1a6fdf1e26e1d69d22ea9c1126fe3c0e1e532",
      "date": "2025-10-31",
      "timestamp": "2025-10-31T13:05:32+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.28381642,
      "net_ltc": 1.28381642,
      "price_usd": 95.38
    },
    {
      "txid": "90e2ff9d8120a174731fb58fc209b86c719e529d63989ed4daaba20162a06d86",
      "date": "2025-10-31",
      "timestamp": "2025-10-31T13:33:02+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.28381642,
      "net_ltc": -1.28381642,
      "price_usd": 95.38
    },
    {
      "txid": "ccd736b55f94743eff2b81114cfba84d67ac2fc14f2f7cd89316f6444a1af468",
      "date": "2025-11-03",
      "timestamp": "2025-11-03T14:56:01+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 7.19904988,
      "net_ltc": 7.19904988,
      "price_usd": 87.42
    },
    {
      "txid": "17b4ba90f5cc2d68c3c0a864deecf4a42407b9fadb1eb874ad05609fd01d4f5e",
      "date": "2025-11-14",
      "timestamp": "2025-11-14T13:06:10+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 8.24217423,
      "net_ltc": 8.24217423,
      "price_usd": 97.59
    },
    {
      "txid": "41f46cfdffeef617e396121b9b1f4191b27794caf02346761c8a716998d7f773",
      "date": "2025-11-23",
      "timestamp": "2025-11-23T18:23:33+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.10891363,
      "net_ltc": -0.10891363,
      "price_usd": 83.08
    },
    {
      "txid": "b1f4a77e73685d213773d70d708ce55b292cd2f3c0a11e0c24936c0949f6ae4b",
      "date": "2025-11-29",
      "timestamp": "2025-11-29T18:15:50+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.19699998,
      "net_ltc": 1.19699998,
      "price_usd": 83.99
    },
    {
      "txid": "9cc10a24f8757fcc6577889a5745a616fde912e9894f706f7d8a35844a0d7513",
      "date": "2025-11-29",
      "timestamp": "2025-11-29T18:15:50+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 4.97784413,
      "net_ltc": 4.97784413,
      "price_usd": 83.99
    },
    {
      "txid": "c28944b6dd9319eadf2ab48a1bdb59ceb473388a243d98871645f065c8ad5ef4",
      "date": "2025-12-16",
      "timestamp": "2025-12-16T21:16:17+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.19699998,
      "net_ltc": -1.19699998,
      "price_usd": 79.06
    },
    {
      "txid": "6ca2092cc2c02c414a2d7818b746f16f2118eeda5e7120bcfcaed00dc546642b",
      "date": "2025-12-17",
      "timestamp": "2025-12-17T09:09:39+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 11.22880085,
      "net_ltc": 11.22880085,
      "price_usd": 76
    },
    {
      "txid": "b58e6a76cef9ded9910fbea94002378bd987a1b1379755a12fccf57f728f6741",
      "date": "2025-12-18",
      "timestamp": "2025-12-18T22:05:54+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.79123943,
      "net_ltc": 0.79123943,
      "price_usd": 74.25
    },
    {
      "txid": "23915ed8f4974f7528ef1853c41b058baedbb1bb13c1b223965fa3fe035cc834",
      "date": "2025-12-18",
      "timestamp": "2025-12-18T22:16:08+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.79123943,
      "net_ltc": -0.79123943,
      "price_usd": 74.25
    },
    {
      "txid": "8f24589764b87b4be08179adfb777136af340d192b7b1a54ff82f968423d737b",
      "date": "2025-12-20",
      "timestamp": "2025-12-20T00:23:45+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.7099,
      "net_ltc": -1.7099,
      "price_usd": 77.83
    },
    {
      "txid": "7b904e30d72a77540b53c5941ad6cc3982f21ba22b96856a935beb6d3e1d560c",
      "date": "2025-12-22",
      "timestamp": "2025-12-22T09:51:09+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 4.99980001,
      "net_ltc": 4.99980001,
      "price_usd": 77
    },
    {
      "txid": "e64e32450827563faf82314a00f73d2148eeef36794998659297a042285bafb4",
      "date": "2025-12-27",
      "timestamp": "2025-12-27T12:18:33+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 6.4050002,
      "net_ltc": 6.4050002,
      "price_usd": 80.27
    },
    {
      "txid": "b44a6a30fe5efa24777c48deb9d5519b1e619500e84d428acc5e9167fe7d5315",
      "date": "2025-12-29",
      "timestamp": "2025-12-29T16:59:13+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.45889002,
      "net_ltc": 0.45889002,
      "price_usd": 78.23
    },
    {
      "txid": "693e35b1af946e4f7eb37bc435290d983c394a2a4e56bab492ab5f05aa66f9f0",
      "date": "2025-12-29",
      "timestamp": "2025-12-29T20:53:22+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.45889002,
      "net_ltc": -0.45889002,
      "price_usd": 78.23
    },
    {
      "txid": "f0ae24c9da1fea695076cf458477f5f03aaf42a457ecd490597aa769a3e1b207",
      "date": "2025-12-31",
      "timestamp": "2025-12-31T12:21:01+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 6.52934182,
      "net_ltc": 6.52934182,
      "price_usd": 76.74
    },
    {
      "txid": "e39e5486d72f20f8609b9e6e443d2393228eaa013b0ea956da83ad25f32f8ba2",
      "date": "2026-01-02",
      "timestamp": "2026-01-02T11:54:29+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 33.7059414,
      "net_ltc": 33.7059414,
      "price_usd": 81.89
    },
    {
      "txid": "cf0dc42c3bfa3a5ad4b9d607bb030602b3ac15fe749a571cf6c789abdb547605",
      "date": "2026-01-05",
      "timestamp": "2026-01-05T20:18:36+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 33.7059414,
      "net_ltc": -33.7059414,
      "price_usd": 83.47
    },
    {
      "txid": "eca0df279be7abc03804562e3cdde5d1e0540b8ca0f08b60484c471597a4c42a",
      "date": "2026-01-06",
      "timestamp": "2026-01-06T14:31:36+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.17808,
      "net_ltc": 1.17808,
      "price_usd": 83.94
    },
    {
      "txid": "ff891902d41001858afdf5f62287faeec15e365086cba72b82d486fdd577dbc2",
      "date": "2026-01-06",
      "timestamp": "2026-01-06T18:56:35+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.17808,
      "net_ltc": -1.17808,
      "price_usd": 83.94
    },
    {
      "txid": "f866e08f92ef4f6aaeb68617c6f374165443e75689db74f0c43e358ae73a0f02",
      "date": "2026-01-07",
      "timestamp": "2026-01-07T13:24:07+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 4.97784413,
      "net_ltc": -4.97784413,
      "price_usd": 81.64
    },
    {
      "txid": "b3b4961c3b51ea2cecbd95a213f6bbea61a15bf0e7757dbb4abb654267d2a62f",
      "date": "2026-01-07",
      "timestamp": "2026-01-07T13:44:22+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 4.99980001,
      "net_ltc": -4.99980001,
      "price_usd": 81.64
    },
    {
      "txid": "4abd82fd295e1cd6a565e00565a832661121c42a09a38c09ab23262fcea859be",
      "date": "2026-01-08",
      "timestamp": "2026-01-08T20:13:20+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 5.21274263,
      "net_ltc": -5.21274263,
      "price_usd": 81.25
    },
    {
      "txid": "756628316bae79670f3e1ad7a9ec9466a50284e0a062b3675b8cfab0e77a89bb",
      "date": "2026-01-09",
      "timestamp": "2026-01-09T13:52:12+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 20.88926466,
      "net_ltc": 20.88926466,
      "price_usd": 81.42
    },
    {
      "txid": "1fabb10f1bae1a1406ec8a295d6f8b8b5e64e555261e6dbfa5d36f3a6fc18fb9",
      "date": "2026-01-09",
      "timestamp": "2026-01-09T15:47:44+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.44449038,
      "net_ltc": 0.44449038,
      "price_usd": 81.42
    },
    {
      "txid": "ac735e7bcac79502a373f5638c125a19612b36eaf946cc5ba91a210764259317",
      "date": "2026-01-09",
      "timestamp": "2026-01-09T19:57:10+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.44449038,
      "net_ltc": -0.44449038,
      "price_usd": 81.42
    },
    {
      "txid": "6456103382fc967871ae79f45ecb835edd24b5231f36e57c79e77b1474ea7edc",
      "date": "2026-01-12",
      "timestamp": "2026-01-12T11:57:32+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 1.91508627,
      "net_ltc": 1.91508627,
      "price_usd": 76.06
    },
    {
      "txid": "a5c7d3203f014e327612bff53e9115b016eab721db9053e9581732a387ec3055",
      "date": "2026-01-12",
      "timestamp": "2026-01-12T16:13:25+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 1.91508627,
      "net_ltc": -1.91508627,
      "price_usd": 76.06
    },
    {
      "txid": "72ccaad507543d86c817140d138ac193287ffdbea13a265466e7e4619dc44ea8",
      "date": "2026-01-13",
      "timestamp": "2026-01-13T23:11:26+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 20.88926466,
      "net_ltc": -20.88926466,
      "price_usd": 78.14
    },
    {
      "txid": "63a3d36411e4bfc11d5faed75e2ff65a772b097afecc1ee6a8939923f0aa3181",
      "date": "2026-01-17",
      "timestamp": "2026-01-17T13:17:35+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.48296106,
      "net_ltc": 0.48296106,
      "price_usd": 74.88
    },
    {
      "txid": "f11f3e7512d1636ceb46c275b8eb23618d0962b155b2ac98f7092e68eab837d2",
      "date": "2026-01-17",
      "timestamp": "2026-01-17T17:41:28+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.48296106,
      "net_ltc": -0.48296106,
      "price_usd": 74.88
    },
    {
      "txid": "2c0bf07f87eb4e5e708bbc57e96cc3e7180ddbcd446ff91fc0d1534a42d9257e",
      "date": "2026-01-19",
      "timestamp": "2026-01-19T10:32:03+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 6.4050002,
      "net_ltc": -6.4050002,
      "price_usd": 70.76
    },
    {
      "txid": "2ae5301c1568e38a801a33d677af0efb80eb30d5c71762ca2a162d043029ede4",
      "date": "2026-01-20",
      "timestamp": "2026-01-20T13:07:27+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 6.52934182,
      "net_ltc": -6.52934182,
      "price_usd": 67.05
    },
    {
      "txid": "8036e6a37940c349dbfdb5523b91879d7e08d342764fc526434b94c34ae4be0a",
      "date": "2026-01-23",
      "timestamp": "2026-01-23T15:10:07+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 12.14398082,
      "net_ltc": 12.14398082,
      "price_usd": 68
    },
    {
      "txid": "ef2ab6fd7a673f7f849e5236643cd69effa5c87ebe739057d6131e05fde296ef",
      "date": "2026-01-24",
      "timestamp": "2026-01-24T22:04:43+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 11.22880085,
      "net_ltc": -11.22880085,
      "price_usd": 68.09
    },
    {
      "txid": "babc1c7d5d04ba2709857d60840e1307cced17e7044eb661116e835beca296b9",
      "date": "2026-01-29",
      "timestamp": "2026-01-29T15:05:42+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.2975846,
      "net_ltc": 0.2975846,
      "price_usd": 66.14
    },
    {
      "txid": "371e2d5463ebe6de8cfacf1f804e6264eeba385441adf0b131b6615cdf8da90d",
      "date": "2026-01-29",
      "timestamp": "2026-01-29T18:55:00+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.2975846,
      "net_ltc": -0.2975846,
      "price_usd": 66.14
    },
    {
      "txid": "a2d5633d05167aecd16d57eb2e6bbc6836dbdd8823f49638c72b9a5caff672bc",
      "date": "2026-02-02",
      "timestamp": "2026-02-02T12:27:16+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 7.01760035,
      "net_ltc": -7.01760035,
      "price_usd": 59.96
    },
    {
      "txid": "58873189ebc524c00f3d8397c17be07a343cc18d502ee4b7af298d3e6871ffc6",
      "date": "2026-02-05",
      "timestamp": "2026-02-05T13:13:43+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 7.19904988,
      "net_ltc": -7.19904988,
      "price_usd": 50.69
    },
    {
      "txid": "40bc483a9b388e8dbaaee9d807ecd88a3104e289bb3131da589f86c0192a6578",
      "date": "2026-02-07",
      "timestamp": "2026-02-07T14:16:22+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 0.92360875,
      "net_ltc": 0.92360875,
      "price_usd": 55.19
    },
    {
      "txid": "d2b69447827ffc0f67b1112a5f3d38aa79349ea9786db09407532e67efbc5008",
      "date": "2026-02-07",
      "timestamp": "2026-02-07T18:07:07+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 0.92360875,
      "net_ltc": -0.92360875,
      "price_usd": 55.19
    },
    {
      "txid": "edd9ab4eb2128d8830709202a790c11cdf1ed5352aa7152c2510fdf1db52f872",
      "date": "2026-02-08",
      "timestamp": "2026-02-08T20:47:53+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 5.83132013,
      "net_ltc": 5.83132013,
      "price_usd": 54.49
    },
    {
      "txid": "7f68e73602f0bc1aeb28949024ba7ca9e3a69b9f0b7a53826e792bca4a22a840",
      "date": "2026-02-09",
      "timestamp": "2026-02-09T05:58:44+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "spend",
      "amount_ltc": 5.83132013,
      "net_ltc": -5.83132013,
      "price_usd": 54.92
    },
    {
      "txid": "781f448612375c4b2cd736fa0ac4d84ab0874d09ca06d9fd08a5a94226866881",
      "date": "2026-02-09",
      "timestamp": "2026-02-09T10:39:21+00:00",
      "addresses": [
        "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
      ],
      "type": "receive",
      "amount_ltc": 13.59871275,
      "net_ltc": 13.59871275,
      "price_usd": 54.92
    }
  ],
  "seen_txids": [
    "ecf038bd7a3381213d258580165e08e91a624c55aeb335bba689f0fdeaa68e13",
    "23915ed8f4974f7528ef1853c41b058baedbb1bb13c1b223965fa3fe035cc834",
    "a5c7d3203f014e327612bff53e9115b016eab721db9053e9581732a387ec3055",
    "3bc38145363abeb36ebcf17b7457800fdf0186aff8f7f39f51a04192af0b5f28",
    "551024e4693f7bdeb02f199f5fa3dac338851232eaa9d3317bdcc888c2552b90",
    "54caa65a5209efadaa4eea547ccb4aa90e47a91b95e57395c479d78320a2c4c5",
    "4b35a8eed9c498177ec9619fd6fb4d826215316f5ed06ed43626b8ff92e0d68f",
    "f9dedd31f57655bff2d58560dca8fdc3e18295eb4453c35f40b0f8af004cf84e",
    "e39e5486d72f20f8609b9e6e443d2393228eaa013b0ea956da83ad25f32f8ba2",
    "2c0bf07f87eb4e5e708bbc57e96cc3e7180ddbcd446ff91fc0d1534a42d9257e",
    "f6d305a83127025714d4582c0469c567add0695bda7d0acd7bc897fe80f57d3b",
    "8f24589764b87b4be08179adfb777136af340d192b7b1a54ff82f968423d737b",
    "a78966a935d76ad9ced71af2c570c54f393c492fd52ebfabf9769ddbb4e9ec5e",
    "4714a88899fc08bec498cca66f647a7eb28275718b89889476ab1ac9b2a58de3",
    "250effdc9ee3f006f658e5f843c6581251d61619d5a50e04678146ae5e2d36a8",
    "f0ae24c9da1fea695076cf458477f5f03aaf42a457ecd490597aa769a3e1b207",
    "08d672ddb56ed1db5a7cb0fb4b5c51dbb4a8ae4732c4d8d911a344f16617d755",
    "1fbcabdba5003cbb3a7f4d94c89c21508a7b361b9bce9b157de080d40591a741",
    "90e2ff9d8120a174731fb58fc209b86c719e529d63989ed4daaba20162a06d86",
    "eca0df279be7abc03804562e3cdde5d1e0540b8ca0f08b60484c471597a4c42a",
    "8036e6a37940c349dbfdb5523b91879d7e08d342764fc526434b94c34ae4be0a",
    "646febd90e3d1ba0f95481f2064a43a95b9f3c9b24a277753afde3b135a65447",
    "92098b82c2f11d97d473184f94e1868a037e4eea090b374164dc2f5e74c79d71",
    "fdf5bbf672936e1127c14c12fce078b3b91bebaf6f52c3a70a141412f54153ec",
    "6af1b726cefc3ebe59471389c167913f086c3d98fe0edf3d0295577c12c7bf25",
    "536a90bc1671374f0cd88b75f8f9bd55480fe05003b6cf1e650fa7d575ad0f81",
    "63a3d36411e4bfc11d5faed75e2ff65a772b097afecc1ee6a8939923f0aa3181",
    "d14ae91c6d73352e58c5928252210c289ada2f06e82801f503bbd5a7c1fc0b20",
    "b58e6a76cef9ded9910fbea94002378bd987a1b1379755a12fccf57f728f6741",
    "2ae5301c1568e38a801a33d677af0efb80eb30d5c71762ca2a162d043029ede4",
    "dfe058b3a74dab8cc754b01f8940009f38b941d622e2e73d4a481cd4fdd2988f",
    "5123db3ba3c30e73bdf8b3dee0c6ba2c5442974dfe1d9cb1b41b55c9fe1167a8",
    "a590ad2b25419fa06ccbc813ab7245eda9a11387427434b196b9234ee6a56b69",
    "6ca2092cc2c02c414a2d7818b746f16f2118eeda5e7120bcfcaed00dc546642b",
    "88b5c95e9fa1492ad7fc741e5566223113ffa2bd84970bdabd40b10d9b91b495",
    "a2d5633d05167aecd16d57eb2e6bbc6836dbdd8823f49638c72b9a5caff672bc",
    "e4315d319a088a4d19e5cd2fc01f9e27f0ee95833b1fc65e29a5b04c2c4f321f",
    "b92ddd54815e60b2d0c028477a1a03263e7ccdb2f749ef07be80588262dbeb6a",
    "7f68e73602f0bc1aeb28949024ba7ca9e3a69b9f0b7a53826e792bca4a22a840",
    "371e2d5463ebe6de8cfacf1f804e6264eeba385441adf0b131b6615cdf8da90d",
    "9cc10a24f8757fcc6577889a5745a616fde912e9894f706f7d8a35844a0d7513",
    "5942aeb2fae01f675e2a63500e61cc261b0058a48755bf54464c9f1d05abf64b",
    "bf6bc5ed8208df05aacb34bcae0be7fbefb059ce847495eac2eaef7b88ddf965",
    "a653a6eb0c2720ddad5dc16dccfc22b75a8325a362069f44bbcba35952c2d9c0",
    "eeae7afc85a5f27e11291d9bc0383c4417c3a4e8ceeebe738e2660ae65daf103",
    "77d7eed5896906806e48c2bcc6d1a6fdf1e26e1d69d22ea9c1126fe3c0e1e532",
    "b1f4a77e73685d213773d70d708ce55b292cd2f3c0a11e0c24936c0949f6ae4b",
    "fddf5a129a1939c68ad99359dbfc017f2fb3f6fad052db12f640d0bf880029d2",
    "302180c3efa01fd5ad9f00394cecc33b696bde807da395d657aed39a200ee605",
    "d2b69447827ffc0f67b1112a5f3d38aa79349ea9786db09407532e67efbc5008",
    "72ccaad507543d86c817140d138ac193287ffdbea13a265466e7e4619dc44ea8",
    "9501cc619ef7d4080576da0d2cc737366885d32a9dda1b7178ce7e571265d535",
    "ff891902d41001858afdf5f62287faeec15e365086cba72b82d486fdd577dbc2",
    "1fabb10f1bae1a1406ec8a295d6f8b8b5e64e555261e6dbfa5d36f3a6fc18fb9",
    "3f5ba0d3d73a8bd01c39a0feacab6bfe2e39fa836208e16944757909431db725",
    "cebb955fce3bfed68046e6fe100a25f1f9d67dc392f3afb291c533ff22e58c53",
    "b8dc2ef75adb56d6dca9687792b586c25375e3cd19bd39df73b5ee52c6917fb7",
    "0fc3e3e73eaa984840bf8696b533d56a3a2aeb77bc05e649080f315a4c2e4442",
    "781f448612375c4b2cd736fa0ac4d84ab0874d09ca06d9fd08a5a94226866881",
    "e64e32450827563faf82314a00f73d2148eeef36794998659297a042285bafb4",
    "84b1951cb4b9112c38bd4cc9427fbfb031cd61c2923dfb0fb703cd02e16d3b5e",
    "f11f3e7512d1636ceb46c275b8eb23618d0962b155b2ac98f7092e68eab837d2",
    "596c4fbcdcc55e2f60422861c0b45c50fb391f204c7e34adf3bbbf0c13b74f5a",
    "b51f179c57f12d573f156994950a8a4f3edca92a04bcbb22ca9e2f39fd318e31",
    "58873189ebc524c00f3d8397c17be07a343cc18d502ee4b7af298d3e6871ffc6",
    "ac735e7bcac79502a373f5638c125a19612b36eaf946cc5ba91a210764259317",
    "f866e08f92ef4f6aaeb68617c6f374165443e75689db74f0c43e358ae73a0f02",
    "ef2ab6fd7a673f7f849e5236643cd69effa5c87ebe739057d6131e05fde296ef",
    "ccd736b55f94743eff2b81114cfba84d67ac2fc14f2f7cd89316f6444a1af468",
    "6456103382fc967871ae79f45ecb835edd24b5231f36e57c79e77b1474ea7edc",
    "fd3425b4b9458b0f308e0786b5f2e07a339e05d7d307d9572cc220434f2309a8",
    "ee2c4085aeebd01b64fd7a83cf031f687284663117d00e33d93d84e7a1c5d3f0",
    "fb7f1f2db1aee55209c4b27adffb4ea564f8c0968423c44254f849ca6fab03a8",
    "dbdf2ab8e1bf55eb11b8bd00efb8f538d8dc8e62d7ed188911345c6173c959c3",
    "d1454e7413e23d8752e2a66f65a6eb500764e6b401da2926c7013982ba948bc8",
    "b3b4961c3b51ea2cecbd95a213f6bbea61a15bf0e7757dbb4abb654267d2a62f",
    "b44a6a30fe5efa24777c48deb9d5519b1e619500e84d428acc5e9167fe7d5315",
    "c28944b6dd9319eadf2ab48a1bdb59ceb473388a243d98871645f065c8ad5ef4",
    "8c6259bf579f4f3030487e9957d2e16056c2bd98ddc95155fb4290b062d88e40",
    "4abd82fd295e1cd6a565e00565a832661121c42a09a38c09ab23262fcea859be",
    "7b904e30d72a77540b53c5941ad6cc3982f21ba22b96856a935beb6d3e1d560c",
    "893f6e46eccfb974a199f83bab93e83093e4578ed65d33d897e5c9bac786e898",
    "0898b1625755041d823272b4a1fb3c5ca2d07a2d1cb8658b59b672da957ca402",
    "a23a6e9e6e9b3748d5805b571c0991350e417ae02fed2a84374dca78442fc9b8",
    "cf0dc42c3bfa3a5ad4b9d607bb030602b3ac15fe749a571cf6c789abdb547605",
    "693e35b1af946e4f7eb37bc435290d983c394a2a4e56bab492ab5f05aa66f9f0",
    "41f46cfdffeef617e396121b9b1f4191b27794caf02346761c8a716998d7f773",
    "ce83ed0020245c85a8128c06cd265ad10311e2eb42b0a89245ac2b87f658808f",
    "61d158cd0347ab633a33d728648c1bc9b551d8eb05902093ec8930f5daee04c9",
    "756628316bae79670f3e1ad7a9ec9466a50284e0a062b3675b8cfab0e77a89bb",
    "edd9ab4eb2128d8830709202a790c11cdf1ed5352aa7152c2510fdf1db52f872",
    "40bc483a9b388e8dbaaee9d807ecd88a3104e289bb3131da589f86c0192a6578",
    "df2beea6e818fb8925060eaca8cb7c27bc98202d714745841444113ec73330c9",
    "17b4ba90f5cc2d68c3c0a864deecf4a42407b9fadb1eb874ad05609fd01d4f5e",
    "dc152bbff35cee425ed8d02a3dc36f9cbfd7f5485edbe548c17be26bb42d1f38",
    "babc1c7d5d04ba2709857d60840e1307cced17e7044eb661116e835beca296b9"
  ],
  "summary": {
    "balance_ltc": 57.31093239,
    "total_received_ltc": 227.7535168,
    "total_spent_ltc": 170.44258441,
    "total_cost_usd": 19266.61,
    "remaining_cost_usd": 4848.17,
    "avg_cost_basis_usd": 84.59,
    "target_profit_pct": 3.0,
    "target_sell_price_usd": 87.13,
    "current_price_usd": 54.95,
    "current_value_usd": 3149.24,
    "unrealized_pl_usd": -1698.93,
    "unrealized_pl_pct": -35.04,
    "total_transactions": 96,
    "total_receives": 49,
    "total_spends": 47
  },
  "last_updated": "2026-02-09T19:50:04.051592+00:00",
  "last_block_height": 3053076,
  "config": {
    "addresses": [
      "ltc1qn4smz8k38des9n6sagh3suavl85020zcshj53l"
    ],
    "target_profit_percent": 3.0,
    "currency": "usd"
  }
};
